# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 242cd9cd41493b434ad2bcb68cbe1c57ca4285644401c26246f083f9ff562344c5c4b6b345f6e69a2a501b9f4ddb33d28f7d0c95207be472f585222098b3376d

test:
  secret_key_base: 0f09c01c34e4326e3cc16ee9d4d6070f42a7dc71f613f1f194cf1d502aa356589e231687d4fb6777bc3ad6fc7c09e65696587a8f17d5de28dec4c8c1597ec03a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
